// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJboxzCal4D3oTX6Qr2LeYtKxCVq6qIyA',
    appId: '1:1077299205570:web:1fdaddd62e55073448f25b',
    messagingSenderId: '1077299205570',
    projectId: 'dodamdodam-94a8a',
    authDomain: 'dodamdodam-94a8a.firebaseapp.com',
    storageBucket: 'dodamdodam-94a8a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMfJEQ4QNY73VZBk-jnPEECX7A82NjJLY',
    appId: '1:1077299205570:android:8e6d3ec4de423ade48f25b',
    messagingSenderId: '1077299205570',
    projectId: 'dodamdodam-94a8a',
    storageBucket: 'dodamdodam-94a8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_oO_C3sxEJIF19hb5Aw98G7KDeFLI9Nw',
    appId: '1:1077299205570:ios:ea57ba5ad252cb6748f25b',
    messagingSenderId: '1077299205570',
    projectId: 'dodamdodam-94a8a',
    storageBucket: 'dodamdodam-94a8a.appspot.com',
    iosClientId: '1077299205570-u64rd7ecqmbe270rv4k0nr01rj9kgt17.apps.googleusercontent.com',
    iosBundleId: 'com.ssafy.a202.app',
  );
}
