server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://dodamdodam.site:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: core
          predicates:
            - Path=/core/**
          uri: lb://CORE
          filters:
            - RewritePath=/core/(?<segment>.*), /$\{segment}
        - id: dodam
          predicates:
            - Path=/dodam/**
          uri: http://70.12.246.36:9090
          filters:
            - RewritePath=/dodam/(?<segment>.*), /$\{segment}
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allow-credentials: false
            allowedHeaders: "*"
            allo정wedMethods: "*"