
# 유레카 서버가 웹 서비스의 성격으로 구동됨
# 포트 번호 지정
server:
  port: 8761

# 마이크로 서비스를 담당하는 스프링 부트 프레임 워크에
# 각각의 마이크로 서비스에 고유한 아이디를 부여하는 설명
spring:
  application:
    name: discoveryService

# Eureka Client 설정
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false


  
  
